!!python/object:nerfstudio.engine.trainer.TrainerConfig
_target: !!python/name:nerfstudio.engine.trainer.Trainer ''
data: &id002 !!python/object/apply:pathlib.PosixPath
- /
- home
- j
- jo
- johnathon
- processed_data
- test
experiment_name: test
gradient_accumulation_steps: {}
load_checkpoint: null
load_config: null
load_dir: null
load_scheduler: true
load_step: null
log_gradients: false
logging: !!python/object:nerfstudio.configs.base_config.LoggingConfig
  local_writer: !!python/object:nerfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:nerfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 10
    stats_to_track: !!python/tuple
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - ETA (time)
  max_buffer_size: 20
  profiler: basic
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:nerfstudio.configs.base_config.MachineConfig
  device_type: cuda
  dist_url: auto
  machine_rank: 0
  num_devices: 1
  num_machines: 1
  seed: 42
max_num_iterations: 30000
method_name: semantic-nerfw
mixed_precision: true
optimizers:
  fields:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: &id001 !!python/name:torch.optim.adam.Adam ''
      eps: 1.0e-15
      lr: 0.01
      max_norm: null
      weight_decay: 0
    scheduler: null
  proposal_networks:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.01
      max_norm: null
      weight_decay: 0
    scheduler: null
output_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- j
- jo
- johnathon
- output
pipeline: !!python/object:nerfstudio.pipelines.base_pipeline.VanillaPipelineConfig
  _target: !!python/name:nerfstudio.pipelines.base_pipeline.VanillaPipeline ''
  datamanager: !!python/object:nerfstudio.data.datamanagers.base_datamanager.VanillaDataManagerConfig
    _target: !!python/object/apply:_operator.getitem
    - !!python/name:nerfstudio.data.datamanagers.base_datamanager.VanillaDataManager ''
    - !!python/name:nerfstudio.data.datasets.semantic_dataset.SemanticDataset ''
    camera_optimizer: null
    camera_res_scale_factor: 1.0
    collate_fn: !!python/name:nerfstudio.data.utils.nerfstudio_collate.nerfstudio_collate ''
    data: *id002
    dataparser: !!python/object:nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig
      _target: !!python/name:nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3D ''
      data: !!python/object/apply:pathlib.PosixPath
      - data
      - sitcoms3d
      - TBBT-big_living_room
      downscale_factor: 4
      include_semantics: true
      scene_scale: 2.0
    eval_image_indices: !!python/tuple
    - 0
    eval_num_images_to_sample_from: -1
    eval_num_rays_per_batch: 8192
    eval_num_times_to_repeat_images: -1
    images_on_gpu: false
    masks_on_gpu: false
    patch_size: 1
    pixel_sampler: !!python/object:nerfstudio.data.pixel_samplers.PixelSamplerConfig
      _target: !!python/name:nerfstudio.data.pixel_samplers.PixelSampler ''
      fisheye_crop_radius: null
      ignore_mask: true
      is_equirectangular: false
      keep_full_image: false
      max_num_iterations: 100
      num_rays_per_batch: 4096
      rejection_sample_mask: true
    train_num_images_to_sample_from: -1
    train_num_rays_per_batch: 4096
    train_num_times_to_repeat_images: -1
  model: !!python/object:nerfstudio.models.semantic_nerfw.SemanticNerfWModelConfig
    _target: !!python/name:nerfstudio.models.semantic_nerfw.SemanticNerfWModel ''
    appearance_embed_dim: 32
    average_init_density: 1.0
    background_color: last_sample
    base_res: 16
    camera_optimizer: !!python/object:nerfstudio.cameras.camera_optimizers.CameraOptimizerConfig
      _target: !!python/name:nerfstudio.cameras.camera_optimizers.CameraOptimizer ''
      mode: SO3xR3
      optimizer: null
      rot_l2_penalty: 0.001
      scheduler: null
      trans_l2_penalty: 0.01
    collider_params:
      far_plane: 6.0
      near_plane: 2.0
    disable_scene_contraction: false
    distortion_loss_mult: 0.002
    enable_collider: true
    eval_num_rays_per_chunk: 65536
    far_plane: 1000.0
    features_per_level: 2
    hidden_dim: 64
    hidden_dim_color: 64
    hidden_dim_transient: 64
    implementation: tcnn
    interlevel_loss_mult: 1.0
    log2_hashmap_size: 19
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    max_res: 2048
    near_plane: 0.05
    num_levels: 16
    num_nerf_samples_per_ray: 48
    num_proposal_iterations: 2
    num_proposal_samples_per_ray: !!python/tuple
    - 256
    - 96
    orientation_loss_mult: 0.0001
    pass_semantic_gradients: false
    pred_normal_loss_mult: 0.001
    predict_normals: false
    prompt: null
    proposal_initial_sampler: piecewise
    proposal_net_args_list:
    - hidden_dim: 16
      log2_hashmap_size: 17
      max_res: 128
      num_levels: 5
      use_linear: false
    - hidden_dim: 16
      log2_hashmap_size: 17
      max_res: 256
      num_levels: 5
      use_linear: false
    proposal_update_every: 5
    proposal_warmup: 5000
    proposal_weights_anneal_max_num_iters: 1000
    proposal_weights_anneal_slope: 10.0
    semantic_loss_weight: 1.0
    use_appearance_embedding: true
    use_average_appearance_embedding: true
    use_gradient_scaling: false
    use_proposal_weight_anneal: true
    use_same_proposal_network: false
    use_single_jitter: true
    use_transient_embedding: false
project_name: nerfstudio-project
prompt: null
relative_model_dir: !!python/object/apply:pathlib.PosixPath
- nerfstudio_models
save_only_latest_checkpoint: true
start_paused: false
steps_per_eval_all_images: 25000
steps_per_eval_batch: 500
steps_per_eval_image: 500
steps_per_save: 2000
timestamp: 2025-11-14_143034
use_grad_scaler: false
viewer: !!python/object:nerfstudio.configs.base_config.ViewerConfig
  camera_frustum_scale: 0.1
  default_composite_depth: true
  image_format: jpeg
  jpeg_quality: 75
  make_share_url: false
  max_num_display_images: 512
  num_rays_per_chunk: 65536
  quit_on_train_completion: true
  relative_log_filename: viewer_log_filename.txt
  websocket_host: 0.0.0.0
  websocket_port: null
  websocket_port_default: 7007
vis: viewer
